dev
RMasnyuk/sort-table pull request #1
Opened 2019-05-20 13:48 UTC by RMasnyuk

2019-05-21 14:36 UTC, ost-ptk requested changes

2019-05-21 14:36 UTC, gestap commented on main.js
> +
need a link for gh-page
you copy this solution from - https://next.plnkr.co/edit/xoqlOD7IfVOeriG0L4po?p=preview&preview

2019-05-21 14:36 UTC, gestap commented on main.js
> +
need a link for gh-page
you copy this solution from - https://next.plnkr.co/edit/xoqlOD7IfVOeriG0L4po?p=preview&preview

2019-05-22 08:48 UTC, RMasnyuk commented on main.js
> +
No, i didn`t really copy this solution. I tried to do this task step-by-step like on the picture below. Yes, i used this solution to solve the problem, but i did`n copy it. You can notice differences.
![fragment](https://user-images.githubusercontent.com/27281509/58160641-8678be80-7c87-11e9-9466-6d178b1bd96c.PNG)

2019-05-22 11:48 UTC, merged

2019-05-22 11:50 UTC, RMasnyuk commented on main.js
> +
gh-pages : https://rmasnyuk.github.io/sort-table/